# version: "2.29.1"
# services:
#   server:
#     build: .
#     restart: always
#     ports:
#       - 8080:8080
#     depends_on:
#       - mysqldb

#     mysqldb:
#       platform: linux/x86_64
#       image: "mysql:8.0.39-debian"
#       restart: always
#       ports:
#         -3307:3306
#       environment:
#         MYSQL_DATABASE: wera
#         MYSQL_USER: collo
#         MYSQL_PASSWORD: Jesus
#         MYSQL_ROOT_PASSWORD: Jesus